### ISSUE TITLE
Run source conformance testing against sample-source

### ISSUE THREAD

**Issue by mattmoor** [knative-sandbox/sample-source#120] opened 2020-07-09 15:56 UTC
cc @lionelvillard @n3wscott @devguyio

**Comment by vaikas** [comment] 2020-07-09 15:57
isn't this dupe of #73

**Comment by vaikas** [comment] 2020-07-09 15:58
/close
reopen if it's something different.

**Closed by vaikas** 2020-07-09 15:58 UTC

**Comment by mattmoor** [comment] 2020-07-09 18:49
yeah, sorry I was furiously opening while the TOC meeting raged on, so sorry I missed that 😇
